// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inter_node_rpc_service.proto

package com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc;

/**
 * Protobuf type {@code com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotClusterSummaryMessage}
 */
public  final class HotClusterSummaryMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotClusterSummaryMessage)
    HotClusterSummaryMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use HotClusterSummaryMessage.newBuilder() to construct.
  private HotClusterSummaryMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private HotClusterSummaryMessage() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private HotClusterSummaryMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            nodeCount_ = input.readInt32();
            break;
          }
          case 18: {
            com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotNodeSummaryList.Builder subBuilder = null;
            if (hotNodeSummaryList_ != null) {
              subBuilder = hotNodeSummaryList_.toBuilder();
            }
            hotNodeSummaryList_ = input.readMessage(com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotNodeSummaryList.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(hotNodeSummaryList_);
              hotNodeSummaryList_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.PANetworking.internal_static_com_amazon_opendistro_elasticsearch_performanceanalyzer_grpc_HotClusterSummaryMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.PANetworking.internal_static_com_amazon_opendistro_elasticsearch_performanceanalyzer_grpc_HotClusterSummaryMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotClusterSummaryMessage.class, com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotClusterSummaryMessage.Builder.class);
  }

  public static final int NODECOUNT_FIELD_NUMBER = 1;
  private int nodeCount_;
  /**
   * <code>int32 nodeCount = 1;</code>
   */
  public int getNodeCount() {
    return nodeCount_;
  }

  public static final int HOTNODESUMMARYLIST_FIELD_NUMBER = 2;
  private com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotNodeSummaryList hotNodeSummaryList_;
  /**
   * <code>.com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotNodeSummaryList hotNodeSummaryList = 2;</code>
   */
  public boolean hasHotNodeSummaryList() {
    return hotNodeSummaryList_ != null;
  }
  /**
   * <code>.com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotNodeSummaryList hotNodeSummaryList = 2;</code>
   */
  public com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotNodeSummaryList getHotNodeSummaryList() {
    return hotNodeSummaryList_ == null ? com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotNodeSummaryList.getDefaultInstance() : hotNodeSummaryList_;
  }
  /**
   * <code>.com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotNodeSummaryList hotNodeSummaryList = 2;</code>
   */
  public com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotNodeSummaryListOrBuilder getHotNodeSummaryListOrBuilder() {
    return getHotNodeSummaryList();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (nodeCount_ != 0) {
      output.writeInt32(1, nodeCount_);
    }
    if (hotNodeSummaryList_ != null) {
      output.writeMessage(2, getHotNodeSummaryList());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (nodeCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, nodeCount_);
    }
    if (hotNodeSummaryList_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getHotNodeSummaryList());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotClusterSummaryMessage)) {
      return super.equals(obj);
    }
    com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotClusterSummaryMessage other = (com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotClusterSummaryMessage) obj;

    if (getNodeCount()
        != other.getNodeCount()) return false;
    if (hasHotNodeSummaryList() != other.hasHotNodeSummaryList()) return false;
    if (hasHotNodeSummaryList()) {
      if (!getHotNodeSummaryList()
          .equals(other.getHotNodeSummaryList())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NODECOUNT_FIELD_NUMBER;
    hash = (53 * hash) + getNodeCount();
    if (hasHotNodeSummaryList()) {
      hash = (37 * hash) + HOTNODESUMMARYLIST_FIELD_NUMBER;
      hash = (53 * hash) + getHotNodeSummaryList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotClusterSummaryMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotClusterSummaryMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotClusterSummaryMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotClusterSummaryMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotClusterSummaryMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotClusterSummaryMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotClusterSummaryMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotClusterSummaryMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotClusterSummaryMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotClusterSummaryMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotClusterSummaryMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotClusterSummaryMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotClusterSummaryMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotClusterSummaryMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotClusterSummaryMessage)
      com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotClusterSummaryMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.PANetworking.internal_static_com_amazon_opendistro_elasticsearch_performanceanalyzer_grpc_HotClusterSummaryMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.PANetworking.internal_static_com_amazon_opendistro_elasticsearch_performanceanalyzer_grpc_HotClusterSummaryMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotClusterSummaryMessage.class, com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotClusterSummaryMessage.Builder.class);
    }

    // Construct using com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotClusterSummaryMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      nodeCount_ = 0;

      if (hotNodeSummaryListBuilder_ == null) {
        hotNodeSummaryList_ = null;
      } else {
        hotNodeSummaryList_ = null;
        hotNodeSummaryListBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.PANetworking.internal_static_com_amazon_opendistro_elasticsearch_performanceanalyzer_grpc_HotClusterSummaryMessage_descriptor;
    }

    @java.lang.Override
    public com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotClusterSummaryMessage getDefaultInstanceForType() {
      return com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotClusterSummaryMessage.getDefaultInstance();
    }

    @java.lang.Override
    public com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotClusterSummaryMessage build() {
      com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotClusterSummaryMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotClusterSummaryMessage buildPartial() {
      com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotClusterSummaryMessage result = new com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotClusterSummaryMessage(this);
      result.nodeCount_ = nodeCount_;
      if (hotNodeSummaryListBuilder_ == null) {
        result.hotNodeSummaryList_ = hotNodeSummaryList_;
      } else {
        result.hotNodeSummaryList_ = hotNodeSummaryListBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotClusterSummaryMessage) {
        return mergeFrom((com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotClusterSummaryMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotClusterSummaryMessage other) {
      if (other == com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotClusterSummaryMessage.getDefaultInstance()) return this;
      if (other.getNodeCount() != 0) {
        setNodeCount(other.getNodeCount());
      }
      if (other.hasHotNodeSummaryList()) {
        mergeHotNodeSummaryList(other.getHotNodeSummaryList());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotClusterSummaryMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotClusterSummaryMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int nodeCount_ ;
    /**
     * <code>int32 nodeCount = 1;</code>
     */
    public int getNodeCount() {
      return nodeCount_;
    }
    /**
     * <code>int32 nodeCount = 1;</code>
     */
    public Builder setNodeCount(int value) {
      
      nodeCount_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 nodeCount = 1;</code>
     */
    public Builder clearNodeCount() {
      
      nodeCount_ = 0;
      onChanged();
      return this;
    }

    private com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotNodeSummaryList hotNodeSummaryList_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotNodeSummaryList, com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotNodeSummaryList.Builder, com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotNodeSummaryListOrBuilder> hotNodeSummaryListBuilder_;
    /**
     * <code>.com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotNodeSummaryList hotNodeSummaryList = 2;</code>
     */
    public boolean hasHotNodeSummaryList() {
      return hotNodeSummaryListBuilder_ != null || hotNodeSummaryList_ != null;
    }
    /**
     * <code>.com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotNodeSummaryList hotNodeSummaryList = 2;</code>
     */
    public com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotNodeSummaryList getHotNodeSummaryList() {
      if (hotNodeSummaryListBuilder_ == null) {
        return hotNodeSummaryList_ == null ? com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotNodeSummaryList.getDefaultInstance() : hotNodeSummaryList_;
      } else {
        return hotNodeSummaryListBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotNodeSummaryList hotNodeSummaryList = 2;</code>
     */
    public Builder setHotNodeSummaryList(com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotNodeSummaryList value) {
      if (hotNodeSummaryListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        hotNodeSummaryList_ = value;
        onChanged();
      } else {
        hotNodeSummaryListBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotNodeSummaryList hotNodeSummaryList = 2;</code>
     */
    public Builder setHotNodeSummaryList(
        com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotNodeSummaryList.Builder builderForValue) {
      if (hotNodeSummaryListBuilder_ == null) {
        hotNodeSummaryList_ = builderForValue.build();
        onChanged();
      } else {
        hotNodeSummaryListBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotNodeSummaryList hotNodeSummaryList = 2;</code>
     */
    public Builder mergeHotNodeSummaryList(com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotNodeSummaryList value) {
      if (hotNodeSummaryListBuilder_ == null) {
        if (hotNodeSummaryList_ != null) {
          hotNodeSummaryList_ =
            com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotNodeSummaryList.newBuilder(hotNodeSummaryList_).mergeFrom(value).buildPartial();
        } else {
          hotNodeSummaryList_ = value;
        }
        onChanged();
      } else {
        hotNodeSummaryListBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotNodeSummaryList hotNodeSummaryList = 2;</code>
     */
    public Builder clearHotNodeSummaryList() {
      if (hotNodeSummaryListBuilder_ == null) {
        hotNodeSummaryList_ = null;
        onChanged();
      } else {
        hotNodeSummaryList_ = null;
        hotNodeSummaryListBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotNodeSummaryList hotNodeSummaryList = 2;</code>
     */
    public com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotNodeSummaryList.Builder getHotNodeSummaryListBuilder() {
      
      onChanged();
      return getHotNodeSummaryListFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotNodeSummaryList hotNodeSummaryList = 2;</code>
     */
    public com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotNodeSummaryListOrBuilder getHotNodeSummaryListOrBuilder() {
      if (hotNodeSummaryListBuilder_ != null) {
        return hotNodeSummaryListBuilder_.getMessageOrBuilder();
      } else {
        return hotNodeSummaryList_ == null ?
            com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotNodeSummaryList.getDefaultInstance() : hotNodeSummaryList_;
      }
    }
    /**
     * <code>.com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotNodeSummaryList hotNodeSummaryList = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotNodeSummaryList, com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotNodeSummaryList.Builder, com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotNodeSummaryListOrBuilder> 
        getHotNodeSummaryListFieldBuilder() {
      if (hotNodeSummaryListBuilder_ == null) {
        hotNodeSummaryListBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotNodeSummaryList, com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotNodeSummaryList.Builder, com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotNodeSummaryListOrBuilder>(
                getHotNodeSummaryList(),
                getParentForChildren(),
                isClean());
        hotNodeSummaryList_ = null;
      }
      return hotNodeSummaryListBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotClusterSummaryMessage)
  }

  // @@protoc_insertion_point(class_scope:com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotClusterSummaryMessage)
  private static final com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotClusterSummaryMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotClusterSummaryMessage();
  }

  public static com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotClusterSummaryMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<HotClusterSummaryMessage>
      PARSER = new com.google.protobuf.AbstractParser<HotClusterSummaryMessage>() {
    @java.lang.Override
    public HotClusterSummaryMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new HotClusterSummaryMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<HotClusterSummaryMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<HotClusterSummaryMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotClusterSummaryMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

