// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inter_node_rpc_service.proto

package com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc;

public interface HotClusterSummaryMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotClusterSummaryMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 nodeCount = 1;</code>
   */
  int getNodeCount();

  /**
   * <code>.com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotNodeSummaryList hotNodeSummaryList = 2;</code>
   */
  boolean hasHotNodeSummaryList();
  /**
   * <code>.com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotNodeSummaryList hotNodeSummaryList = 2;</code>
   */
  com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotNodeSummaryList getHotNodeSummaryList();
  /**
   * <code>.com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotNodeSummaryList hotNodeSummaryList = 2;</code>
   */
  com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotNodeSummaryListOrBuilder getHotNodeSummaryListOrBuilder();
}
