// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inter_node_rpc_service.proto

package com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc;

public interface HotNodeSummaryListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotNodeSummaryList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotNodeSummaryMessage hotNodeSummary = 1;</code>
   */
  java.util.List<com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotNodeSummaryMessage> 
      getHotNodeSummaryList();
  /**
   * <code>repeated .com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotNodeSummaryMessage hotNodeSummary = 1;</code>
   */
  com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotNodeSummaryMessage getHotNodeSummary(int index);
  /**
   * <code>repeated .com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotNodeSummaryMessage hotNodeSummary = 1;</code>
   */
  int getHotNodeSummaryCount();
  /**
   * <code>repeated .com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotNodeSummaryMessage hotNodeSummary = 1;</code>
   */
  java.util.List<? extends com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotNodeSummaryMessageOrBuilder> 
      getHotNodeSummaryOrBuilderList();
  /**
   * <code>repeated .com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotNodeSummaryMessage hotNodeSummary = 1;</code>
   */
  com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotNodeSummaryMessageOrBuilder getHotNodeSummaryOrBuilder(
      int index);
}
