// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inter_node_rpc_service.proto

package com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc;

public interface HotNodeSummaryMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotNodeSummaryMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string nodeID = 1;</code>
   */
  java.lang.String getNodeID();
  /**
   * <code>string nodeID = 1;</code>
   */
  com.google.protobuf.ByteString
      getNodeIDBytes();

  /**
   * <code>string hostAddress = 2;</code>
   */
  java.lang.String getHostAddress();
  /**
   * <code>string hostAddress = 2;</code>
   */
  com.google.protobuf.ByteString
      getHostAddressBytes();

  /**
   * <code>.com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotResourceSummaryList hotResourceSummaryList = 3;</code>
   */
  boolean hasHotResourceSummaryList();
  /**
   * <code>.com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotResourceSummaryList hotResourceSummaryList = 3;</code>
   */
  com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotResourceSummaryList getHotResourceSummaryList();
  /**
   * <code>.com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotResourceSummaryList hotResourceSummaryList = 3;</code>
   */
  com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotResourceSummaryListOrBuilder getHotResourceSummaryListOrBuilder();

  /**
   * <code>.com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotShardSummaryList hotShardSummaryList = 4;</code>
   */
  boolean hasHotShardSummaryList();
  /**
   * <code>.com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotShardSummaryList hotShardSummaryList = 4;</code>
   */
  com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotShardSummaryList getHotShardSummaryList();
  /**
   * <code>.com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotShardSummaryList hotShardSummaryList = 4;</code>
   */
  com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotShardSummaryListOrBuilder getHotShardSummaryListOrBuilder();
}
