// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inter_node_rpc_service.proto

package com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc;

public interface HotResourceSummaryListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotResourceSummaryList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotResourceSummaryMessage hotResourceSummary = 1;</code>
   */
  java.util.List<com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotResourceSummaryMessage> 
      getHotResourceSummaryList();
  /**
   * <code>repeated .com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotResourceSummaryMessage hotResourceSummary = 1;</code>
   */
  com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotResourceSummaryMessage getHotResourceSummary(int index);
  /**
   * <code>repeated .com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotResourceSummaryMessage hotResourceSummary = 1;</code>
   */
  int getHotResourceSummaryCount();
  /**
   * <code>repeated .com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotResourceSummaryMessage hotResourceSummary = 1;</code>
   */
  java.util.List<? extends com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotResourceSummaryMessageOrBuilder> 
      getHotResourceSummaryOrBuilderList();
  /**
   * <code>repeated .com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotResourceSummaryMessage hotResourceSummary = 1;</code>
   */
  com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotResourceSummaryMessageOrBuilder getHotResourceSummaryOrBuilder(
      int index);
}
