// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inter_node_rpc_service.proto

package com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc;

public interface HotShardSummaryListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotShardSummaryList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotShardSummaryMessage hotShardSummary = 1;</code>
   */
  java.util.List<com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotShardSummaryMessage> 
      getHotShardSummaryList();
  /**
   * <code>repeated .com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotShardSummaryMessage hotShardSummary = 1;</code>
   */
  com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotShardSummaryMessage getHotShardSummary(int index);
  /**
   * <code>repeated .com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotShardSummaryMessage hotShardSummary = 1;</code>
   */
  int getHotShardSummaryCount();
  /**
   * <code>repeated .com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotShardSummaryMessage hotShardSummary = 1;</code>
   */
  java.util.List<? extends com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotShardSummaryMessageOrBuilder> 
      getHotShardSummaryOrBuilderList();
  /**
   * <code>repeated .com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotShardSummaryMessage hotShardSummary = 1;</code>
   */
  com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.HotShardSummaryMessageOrBuilder getHotShardSummaryOrBuilder(
      int index);
}
