// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inter_node_rpc_service.proto

package com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc;

public interface MetricsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.MetricsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string metrics_result = 1;</code>
   */
  java.lang.String getMetricsResult();
  /**
   * <code>string metrics_result = 1;</code>
   */
  com.google.protobuf.ByteString
      getMetricsResultBytes();
}
