// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inter_node_rpc_service.proto

package com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc;

public interface ResourceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.Resource)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.ResourceEnum resource_enum = 1;</code>
   */
  int getResourceEnumValue();
  /**
   * <code>.com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.ResourceEnum resource_enum = 1;</code>
   */
  com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.ResourceEnum getResourceEnum();

  /**
   * <code>.com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.MetricEnum metric_enum = 2;</code>
   */
  int getMetricEnumValue();
  /**
   * <code>.com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.MetricEnum metric_enum = 2;</code>
   */
  com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.MetricEnum getMetricEnum();
}
