// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inter_node_rpc_service.proto

package com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc;

public interface TopConsumerSummaryListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.TopConsumerSummaryList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.TopConsumerSummaryMessage consumer = 1;</code>
   */
  java.util.List<com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.TopConsumerSummaryMessage> 
      getConsumerList();
  /**
   * <code>repeated .com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.TopConsumerSummaryMessage consumer = 1;</code>
   */
  com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.TopConsumerSummaryMessage getConsumer(int index);
  /**
   * <code>repeated .com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.TopConsumerSummaryMessage consumer = 1;</code>
   */
  int getConsumerCount();
  /**
   * <code>repeated .com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.TopConsumerSummaryMessage consumer = 1;</code>
   */
  java.util.List<? extends com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.TopConsumerSummaryMessageOrBuilder> 
      getConsumerOrBuilderList();
  /**
   * <code>repeated .com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.TopConsumerSummaryMessage consumer = 1;</code>
   */
  com.amazon.opendistro.elasticsearch.performanceanalyzer.grpc.TopConsumerSummaryMessageOrBuilder getConsumerOrBuilder(
      int index);
}
